### ISSUE TITLE
Winium Mobile driver is not working on my Windows 10 system

### ISSUE THREAD

**Issue by aman019** [2gis/Winium.Mobile#181]
Bellow error I am getting when I tried to run winium mobile driver.

D:\aman\WiniumMobileDriver>Winium.Mobile.Driver.exe --verbose
16:12:29 [INFO] Winium.Mobile.Driver, Version: 1.7.1.0, Revision: e9c35bb5333e2f7f3b2c30baec883b157db01b34
16:12:29 [FATAL] System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Xde.Common, Version=8.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Xde.Common, Version=8.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Winium.Mobile.Connectivity.Emulator.EmulatorFactory..ctor()
   at Winium.Mobile.Connectivity.Emulator.EmulatorFactory.<.cctor>b__0() in c:\Dev\Winium.StoreApps\Winium\Winium.Mobile.Connectivity\Emulator\EmulatorFactory.cs:line 20
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Winium.Mobile.Driver.Program.Main(String[] args) in c:\Dev\Winium.StoreApps\Winium\Winium.Mobile.Driver\Program.cs:line 63

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].

**Comment by NickAb** [comment]
You need Windows Phone SDK with emulators installed on your host machine

https://developer.microsoft.com/en-us/windows/downloads/sdk-archive

**Comment by aman019** [comment]
Thanks for the reply! Will try after installing SDK and emulators. 

Does this mean winium automation is not possible with real device?

**Comment by NickAb** [comment]
Winium.Mobile supports emulators only, because we were not able to do user input simulation on devices.
But you can relatively easy hack code to use real devices, but you will have to fallback to automation api like Invoke, etc. instead of simulating user touch inputs.

There is also Project My Screen app which mirrors your host desktop input to connected phone, so it should be possible to simulate touch input on devices properly, but this one would require some research.

**Comment by aman019** [comment]
Thanks Nick!

What do yo mean by "But you can ...  touch inputs"? Please help me to understand this.

**Comment by NickAb** [comment]
There are two ways to press button or scroll a list during tests.

You can either simulate user gestures (tap, flick, etc.) or you can call automation api like Invoke or Scroll. Later does not simulate user input, it directly calls code responsible for button action, or scrolling.

**Comment by aman019** [comment]
Hi Nick, As suggested by you i have installed Windows phone SDK and emulator. I am able to launch the windows 10 phone emulator successfully but while trying to run  Winium.Mobile.Driver.exe it is displaying the same error which which i posted earlier.

Please let me know if you need more info from my side to resolve my problem.

**Comment by narayanabojja** [comment]
Hi ,
I am running Winium.Mobile.Driver.exe in Windows 10 system. It is not running . It is opening and closing automatically. I have installed Windows 10 SDK and Windows 10  emulator is starting successfully. If I click muliple times on Winium.Mobile.Driver.exe . It is opening and showing blank screen. I am also attaching screen shots to understand better.
![windows_sdk](https://cloud.githubusercontent.com/assets/18064190/26674152/003a3d9e-46dd-11e7-952d-d21c64852b3d.png)
![winium](https://cloud.githubusercontent.com/assets/18064190/26674153/003c7bcc-46dd-11e7-92a6-bb5e5552a234.png)
